[package]
name = "vest-providers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
tokio.workspace = true
reqwest.workspace = true
backon.workspace = true
tracing.workspace = true
futures.workspace = true

vest-core = { workspace = true }
vest-config = { workspace = true }
