use chrono::Utc;
use rand::Rng;
use vest_core::ids::new_id;
use vest_core::types::*;

impl Default for FindingFactory {
    fn default() -> Self {
        Self::new()
    }
}

pub struct FindingFactory {
    id: String,
    scan_id: String,
    target_id: String,
    title: String,
    description: String,
    vulnerability_class: VulnerabilityClass,
    severity: Severity,
    confidence: f64,
    status: FindingStatus,
    cvss_score: Option<f64>,
    cve_id: Option<String>,
    cwe_id: Option<String>,
    evidence: serde_json::Value,
    poc: Option<String>,
    remediation: Option<String>,
    location: serde_json::Value,
    false_positive_history: Option<serde_json::Value>,
    tags: Vec<String>,
    metadata: serde_json::Value,
}

impl FindingFactory {
    pub fn new() -> Self {
        Self {
            id: new_id(),
            scan_id: "factory-scan".into(),
            target_id: "factory-target".into(),
            title: "Factory Finding".into(),
            description: "Generated by test factory".into(),
            vulnerability_class: VulnerabilityClass::Unknown,
            severity: Severity::Medium,
            confidence: 0.75,
            status: FindingStatus::Open,
            cvss_score: None,
            cve_id: None,
            cwe_id: None,
            evidence: serde_json::json!({"factory": true}),
            poc: None,
            remediation: None,
            location: serde_json::json!({"factory": "test"}),
            false_positive_history: None,
            tags: vec!["factory".into()],
            metadata: serde_json::json!({}),
        }
    }

    pub fn random() -> Self {
        let mut rng = rand::thread_rng();
        let sevs = [
            Severity::Critical,
            Severity::High,
            Severity::Medium,
            Severity::Low,
            Severity::Info,
        ];
        let classes = [
            VulnerabilityClass::BufferOverflow,
            VulnerabilityClass::XSS,
            VulnerabilityClass::SQLInjection,
            VulnerabilityClass::Unknown,
        ];
        let statuses = [
            FindingStatus::Open,
            FindingStatus::Confirmed,
            FindingStatus::FalsePositive,
        ];

        Self::new()
            .title(format!("Finding-{}", rng.gen::<u32>()))
            .severity(sevs[rng.gen_range(0..sevs.len())])
            .vulnerability_class(classes[rng.gen_range(0..classes.len())])
            .confidence(rng.gen::<f64>())
            .status(statuses[rng.gen_range(0..statuses.len())])
            .cvss_score(Some(rng.gen_range(0.0..10.0)))
    }

    pub fn critical() -> Self {
        Self::new()
            .severity(Severity::Critical)
            .confidence(0.95)
            .cvss_score(Some(9.8))
    }
    pub fn high() -> Self {
        Self::new()
            .severity(Severity::High)
            .confidence(0.85)
            .cvss_score(Some(7.5))
    }
    pub fn medium() -> Self {
        Self::new()
            .severity(Severity::Medium)
            .confidence(0.7)
            .cvss_score(Some(5.5))
    }
    pub fn low() -> Self {
        Self::new()
            .severity(Severity::Low)
            .confidence(0.5)
            .cvss_score(Some(2.5))
    }
    pub fn info() -> Self {
        Self::new().severity(Severity::Info).confidence(0.3)
    }

    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.id = id.into();
        self
    }
    pub fn title(mut self, t: impl Into<String>) -> Self {
        self.title = t.into();
        self
    }
    pub fn severity(mut self, s: Severity) -> Self {
        self.severity = s;
        self
    }
    pub fn vulnerability_class(mut self, v: VulnerabilityClass) -> Self {
        self.vulnerability_class = v;
        self
    }
    pub fn confidence(mut self, c: f64) -> Self {
        self.confidence = c;
        self
    }
    pub fn status(mut self, s: FindingStatus) -> Self {
        self.status = s;
        self
    }
    pub fn cvss_score(mut self, s: Option<f64>) -> Self {
        self.cvss_score = s;
        self
    }
    pub fn cwe(mut self, c: impl Into<String>) -> Self {
        self.cwe_id = Some(c.into());
        self
    }
    pub fn description(mut self, d: impl Into<String>) -> Self {
        self.description = d.into();
        self
    }
    pub fn target_id(mut self, id: impl Into<String>) -> Self {
        self.target_id = id.into();
        self
    }

    pub fn build(self) -> Finding {
        let now = Utc::now();
        Finding {
            id: self.id,
            scan_id: self.scan_id,
            target_id: self.target_id,
            title: self.title,
            description: self.description,
            vulnerability_class: self.vulnerability_class,
            severity: self.severity,
            confidence: self.confidence,
            status: self.status,
            cvss_score: self.cvss_score,
            cve_id: self.cve_id,
            cwe_id: self.cwe_id,
            evidence: self.evidence,
            poc: self.poc,
            remediation: self.remediation,
            location: self.location,
            false_positive_history: self.false_positive_history,
            tags: self.tags,
            metadata: self.metadata,
            discovered_at: now,
            updated_at: now,
        }
    }
}

impl Default for TargetFactory {
    fn default() -> Self {
        Self::new()
    }
}

pub struct TargetFactory {
    target_type: TargetType,
    name: String,
}

impl TargetFactory {
    pub fn new() -> Self {
        Self {
            target_type: TargetType::Web,
            name: "factory.local".into(),
        }
    }
    pub fn web(url: &str) -> Self {
        Self {
            target_type: TargetType::Web,
            name: url.into(),
        }
    }
    pub fn binary(path: &str) -> Self {
        Self {
            target_type: TargetType::Binary,
            name: path.into(),
        }
    }
    pub fn process(pid: u32) -> Self {
        Self {
            target_type: TargetType::Process,
            name: format!("pid-{}", pid),
        }
    }
    pub fn network(host: &str) -> Self {
        Self {
            target_type: TargetType::Network,
            name: host.into(),
        }
    }

    pub fn build(self) -> Target {
        let now = Utc::now();
        let (path, url_str, pid, host) = match self.target_type {
            TargetType::Web => (None, Some(format!("https://{}", self.name)), None, None),
            TargetType::Binary => (Some(self.name.clone()), None, None, None),
            TargetType::Process => (None, None, Some(12345), None),
            TargetType::Network => (None, None, None, Some(self.name.clone())),
            _ => (None, None, None, None),
        };
        Target {
            id: new_id(),
            name: self.name,
            target_type: self.target_type,
            path,
            url_str,
            pid,
            host,
            metadata: serde_json::json!({}),
            created_at: now,
            updated_at: now,
        }
    }
}

impl Default for ScanSessionFactory {
    fn default() -> Self {
        Self::new()
    }
}

pub struct ScanSessionFactory {
    mode: ScanMode,
    status: ScanStatus,
    target_id: String,
}

impl ScanSessionFactory {
    pub fn new() -> Self {
        Self {
            mode: ScanMode::Pipeline,
            status: ScanStatus::Pending,
            target_id: "factory-target".into(),
        }
    }
    pub fn mode(mut self, m: ScanMode) -> Self {
        self.mode = m;
        self
    }
    pub fn status(mut self, s: ScanStatus) -> Self {
        self.status = s;
        self
    }
    pub fn completed(mut self) -> Self {
        self.status = ScanStatus::Completed;
        self
    }

    pub fn build(self) -> ScanSession {
        let now = Utc::now();
        ScanSession {
            id: new_id(),
            target_id: self.target_id,
            mode: self.mode,
            config: serde_json::json!({}),
            status: self.status,
            agent_model: Some("test-model".into()),
            started_at: Some(now),
            completed_at: if self.status == ScanStatus::Completed {
                Some(now)
            } else {
                None
            },
            duration_ms: Some(1000),
            total_findings: 0,
            critical_count: 0,
            high_count: 0,
            medium_count: 0,
            low_count: 0,
            info_count: 0,
            metadata: serde_json::json!({}),
            created_at: now,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_finding_factory_creates_valid_finding() {
        let finding = FindingFactory::critical()
            .title("Buffer Overflow")
            .cwe("CWE-120")
            .build();
        assert_eq!(finding.severity, Severity::Critical);
        assert_eq!(finding.confidence, 0.95);
        assert_eq!(finding.cwe_id, Some("CWE-120".into()));
    }

    #[test]
    fn test_finding_factory_random_produces_different() {
        let f1 = FindingFactory::random().build();
        let f2 = FindingFactory::random().build();
        assert!(f1.id != f2.id || f1.title != f2.title || f1.confidence != f2.confidence);
    }

    #[test]
    fn test_target_factory_web() {
        let target = TargetFactory::web("example.com").build();
        assert_eq!(target.target_type, TargetType::Web);
        assert_eq!(target.url_str, Some("https://example.com".into()));
    }

    #[test]
    fn test_scan_session_factory() {
        let scan = ScanSessionFactory::new().completed().build();
        assert_eq!(scan.status, ScanStatus::Completed);
        assert!(scan.completed_at.is_some());
    }

    #[test]
    fn test_finding_factory_all_severities() {
        for sev in &[
            Severity::Critical,
            Severity::High,
            Severity::Medium,
            Severity::Low,
            Severity::Info,
        ] {
            let f = FindingFactory::new().severity(*sev).build();
            assert_eq!(f.severity, *sev);
        }
    }
}
