[package]
name = "vest-scanner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
goblin.workspace = true
capstone.workspace = true
iced-x86.workspace = true
reqwest.workspace = true
tracing.workspace = true
regex = "1"
chromiumoxide = { workspace = true, features = ["tokio-runtime"] }
ureq = { workspace = true }

vest-core = { workspace = true }

[dev-dependencies]
rand = "0.8"
